name: Deploy to Production

on:
  push:
    branches:
      - main2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH Host Key
      run: |
        ssh-keyscan test.skillnaav.com >> ~/.ssh/known_hosts

    - name: Start SSH Agent
      run: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa

    - name: Deploy to server
      run: |
        ssh ubuntu@test.skillnaav.com 'bash /home/ubuntu/skillnaav-fullstack/deploy.sh'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
