name: Deploy

on:
  push:
    branches:
      - main2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4' # Adjust according to your local setup

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          CI=false npm run build

      - name: Deploy to server
        run: |
          scp -r frontend/build/* ubuntu@test.skillnaav.com:/home/ubuntu/skillnaav-fullstack/frontend/build

      - name: SSH into server and run deploy script
        run: |
          ssh ubuntu@test.skillnaav.com 'bash -s' < /home/runner/work/skillnaav-fullstack/skillnaav-fullstack/deploy.sh
