name: Deploy to Server

on:
  push:
    branches:
      - uday10-03-25  # This workflow runs only when pushing to this branch
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Get Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV  # Extract branch name

      - name: Run deployment script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@www.skillnaav.com << 'EOF'
            cd /home/ubuntu/skillnaav-fullstack
            ./deploy.sh "$BRANCH_NAME"
          EOF
