name: Deploy to Server

on:
  push:
    branches:
      - main-prod18-09

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH for GitHub Actions
      run: |
        mkdir -p ~/.ssh
        echo "Host test.skillnaav.com" >> ~/.ssh/config
        echo "    Hostname test.skillnaav.com" >> ~/.ssh/config
        echo "    User ubuntu" >> ~/.ssh/config
        echo "    HostKeyAlgorithms +ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519" >> ~/.ssh/config
        echo "    PubkeyAcceptedAlgorithms +ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519" >> ~/.ssh/config
        ssh-keyscan -H test.skillnaav.com >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        scp -r frontend/build/* ubuntu@test.skillnaav.com:/home/ubuntu/skillnaav-fullstack/frontend/build
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
